In [1]:
import numpy as np
import pandas as pd
from sklearn import metrics

In [2]:
Data_Frame = pd.read_csv("F:\\personal\\training\\python\\PythonClinic\\ml-latest-small\\ratings.csv")

In [3]:
Data_Frame

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [4]:
X = Data_Frame.iloc[:,0:2]
X = X.values
Y = Data_Frame['rating']
Y = Y.values*10

In [5]:
np.unique(Y)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [6]:
Y*10

array([400., 400., 400., ..., 500., 500., 300.])

In [7]:
from sklearn.naive_bayes import GaussianNB

In [8]:
from sklearn.naive_bayes import MultinomialNB
clf1 = MultinomialNB(alpha=1.0, fit_prior=True)
model = GaussianNB()

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.2, random_state=42)

In [10]:
model.fit(X_train , Y_train)

GaussianNB()

In [11]:
ypred = model.predict(X_test)

In [12]:
ypred/10

array([4., 4., 4., ..., 4., 4., 4.])

In [13]:
metrics.confusion_matrix(Y_test, ypred)

array([[   0,    0,    1,    0,    0,    0,   18,  258,   12,    0],
       [   0,    0,    1,    0,    0,    0,   21,  520,   14,    0],
       [   0,    0,    2,    0,    0,    0,   38,  334,   18,    0],
       [   0,    0,    1,    0,    0,    0,   74, 1429,   29,    0],
       [   0,    0,    2,    0,    0,    0,   87,  960,   31,    0],
       [   0,    0,    8,    0,    0,    0,  156, 3766,   49,    0],
       [   0,    0,    7,    0,    0,    0,  200, 2355,   86,    0],
       [   0,    0,    8,    0,    0,    0,  234, 4940,  129,    0],
       [   0,    0,    3,    0,    0,    0,  119, 1535,   75,    0],
       [   0,    0,    1,    0,    0,    0,   95, 2483,   69,    0]],
      dtype=int64)

In [15]:
metrics.accuracy_score(Y_test, ypred) 

62.867711225704085

In [52]:
Y_test

array([45., 30., 30., ..., 45., 30., 30.])